scoutapp/scout_apm_ruby

CHANGELOG.markdown, lib/scout_apm/framework_integrations/rails_3_or_4.rb, lib/scout_apm/version.rb
This is done to address a weird edge case: the textacular gem overwrites `ActiveRecord::Base#respond_to?` and establishes an AR connection. 
This was unexpected and resulted in our threads creating many Postgres connections. The updated code uses a universal way to access the AR adapter (and is less code). We assume other gems are less likely to overwrite `ActiveRecord::Base.configurations`.
Bumps version to 1.2.9.pre.
=> Using ActiveRecord::Base.configurations in Rails 3-4

lib/scout_apm/config.rb, lib/scout_apm/instruments/action_controller_rails_2.rb, lib/scout_apm/instruments/action_controller_rails_3_rails4.rb
For customers that don't want URL params propagated into Scout. Default is fullpath.
=> uri reporting config option (path or fullpath)

CHANGELOG.markdown, lib/scout_apm/framework_integrations/rails_3_or_4.rb, lib/scout_apm/instruments/active_record.rb, lib/scout_apm/layer_converter.rb, lib/scout_apm/utils/sql_sanitizer.rb, lib/scout_apm/utils/sql_sanitizer_regex.rb, lib/scout_apm/utils/sql_sanitizer_regex_1_8_7.rb, lib/scout_apm/version.rb
Previously, we were sanitizing SQL queries as layers were added. Now, we sanitize only where it is needed: `LayerSlowTransactionConverter`. This results in large performance gains:
* overhead benchmarks drop from 8.1% to 3.2%
* stackprof samples for `ScoutApm::Utils::SqlSanitizer#to_s_postgres` drop from 1.2% to 0%
This also addresses a couple other higher-sample % numbers from stackprof output:
* Memo-izing fetching the database driver
* Using strip! vs. gsub!
This needs to run on production environments first before merging.
=> Lazy sanitization of SQL, and a couple of performance improvements

lib/scout_apm.rb, lib/scout_apm/layer_converter.rb, lib/scout_apm/layer_converters/object_allocation.rb, lib/scout_apm/tracked_request.rb, lib/scout_apm/version.rb
Previously, allocation metrics were only stored at the controller-level. Now, they are scoped under the controller (just like timing metrics). Also:
* Start of some refactoring to move LayerConverters into separate files.
* Passing the object allocation count via call_count vs. updating timing (messes with server-side things).
=> Storing scoped object allocation metrics

ext/stack_profile/stack_profile.c, lib/scout_apm/layer.rb, lib/scout_apm/layer_converters/object_allocation.rb, lib/scout_apm/tracked_request.rb
We reset the allocation count when we record it when a layer is completed. This means that allocations that occur between the start of a parent layer (ex: Controller) and a child layer (ex: ActiveRecord) are attributed entirely to the child.
This fixes the issue - it mirrors how we calculate timing numbers closely.
=> Fixing allocating objects to parent layers

CHANGELOG.markdown, lib/scout_apm.rb, lib/scout_apm/call_set.rb, lib/scout_apm/environment.rb, lib/scout_apm/layer.rb, lib/scout_apm/layer_converters/slow_job_converter.rb, lib/scout_apm/layer_converters/slow_request_converter.rb, lib/scout_apm/layer_converters/slow_transaction_converter.rb, lib/scout_apm/metric_meta.rb, lib/scout_apm/slow_transaction.rb, lib/scout_apm/tracked_request.rb, lib/scout_apm/utils/active_record_metric_name.rb, lib/scout_apm/utils/backtrace_parser.rb, lib/scout_apm/utils/sql_sanitizer.rb, lib/scout_apm/version.rb
This implements a performance-compliant version of n+1 backtrace colllection. 
See #36 for the original start.
We'll want to add this to jobs after running this for a bit.
=> Background jobs n+1 w/CallSet

lib/scout_apm/layer_converters/slow_request_converter.rb
This change handles a bug where [the default `ignore_traces` setting (which is an empty array)](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/config.rb#L33) gets converted to `nil` and then `each` is called, raising an exception.
The `nil` conversion is due to the fact that there is [a length check in the `#value` method](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/config.rb#L58), that if zero returns `nil`.
I used the `(value || [])` approach here as I noticed that style being used for [the `disabled_instruments` option](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/agent.rb#L287). That said, it ultimately seems like the logic for reading values out of the config should handle arrays as first-class citizens. Setting …
=> Handle nil ignore_traces when ignoring trace patterns

lib/scout_apm/config.rb, lib/scout_apm/deploy_integrations/capistrano_3.rb
Addresses https://github.com/scoutapp/scout_apm_ruby/issues/43
This isn't intended to fix deploy tracking for everyone everywhere, just makes it work for us again so we can see a real deploy record for APM.
=> when fetching the app name for the post-deploy hook, use the deploy-to environment when possible (as represented by Capistrano stage)

lib/scout_apm/instant/middleware.rb
Ran into this when testing out the latest gem version locally on Ruby 1.8.7.
=> Use 1.8 compatible hash syntax in Instant::Middleware

CHANGELOG.markdown, lib/scout_apm/instruments/action_controller_rails_2.rb, lib/scout_apm/instruments/action_controller_rails_3_rails4.rb, lib/scout_apm/version.rb
Applying `filtered_parameters` settings to Rails 3+ trace uris. For Rails 2, just reporting the path.
These are better security-by-default settings for transaction trace uris. Example formatting of URIs for Rails 3+ reported to Scout:
`/users?password=secret&limit=10 => /users?password=[FILTERED]&limit=10`
=> Better security-by-default for Transaction Trace URIs

CHANGELOG.markdown, lib/scout_apm/context.rb, test/unit/context_test.rb
This brings down our logging output when handling issues with invalid Context keys and values:
* Not logging errors w/nil keys or values
* Bumping log level down from `WARN` => `INFO`
A unit test has also been added for Context.
=> Less noisy output on errors with Context.

lib/scout_apm/utils/backtrace_parser.rb, test/unit/utils/backtrace_parser_test.rb
If you're in the Rails root, and inside lib/ app/ or config/, then you
are.  This prevents directories like vendor/ from showing up in the UI
as code the user owns directly.
=> This refines what it means to be "in-app" when it comes to backtraces

lib/scout_apm/instruments/grape.rb
The API is slightly different in older versions of Grape vs the existing
instrumentation developed against 0.16.
Tested from 0.10.0 onward
=> Accomodate older Grape versions

lib/scout_apm/agent.rb
Also adds safety around the call that actually broke if you called
shutdown twice.
The case this happened is in Passenger integration, where we have a hook
for the `stopping_worker_process` event, which called shutdown.  Then
the process actually stopped, which fired our at_exit handler, causing
shutdown to be called a second time.  That second time attempted to work
with the background thread that had been finished in the first call,
causing an error message to be emitted.
=> Only call shutdown once per process.

lib/scout_apm/layer_converters/converter_base.rb, lib/scout_apm/layer_converters/slow_job_converter.rb, lib/scout_apm/layer_converters/slow_request_converter.rb, lib/scout_apm/serializers/slow_jobs_serializer_to_json.rb, lib/scout_apm/slow_job_record.rb, lib/scout_apm/slow_transaction.rb
This also implements a cap on the number of metrics stored in any given
trace (500 currently).  This is a number beyond what the majority of
requests hit, but should help prevent performance hits and giant payloads.
=> Refactor SlowRequestConverter and SlowJobConverter to merge shared logic

lib/scout_apm/instruments/net_http.rb, scout_apm.gemspec, test/unit/instruments/net_http_test.rb
I've application code using Addressable::URI thus
addressable_uri = Addressable::URI.parse(uri)
Net::HTTP.get(addressable_uri)
This break with an exception being thrown by
`lib/scout_apm/instruments/net_http.rb`. One possilbe solution would be
addressable_uri = URI(uri)
Net::HTTP.get(addressable_uri)
But I'm on ruby 2.1.9 and have to handle subdomains with underscores,
see https://bugs.ruby-lang.org/issues/9974. So until I can update ruby >
2.1 my application code breaks with scout_apm.
This commit make scout_apm request profiling usable with both
Addressable::URI and URI.
=> Handle Addressable::URI in addition to URI

lib/scout_apm/layer.rb, lib/scout_apm/layer_converters/converter_base.rb, lib/scout_apm/layer_converters/job_converter.rb, lib/scout_apm/layer_converters/metric_converter.rb
Most Layer objects are leaf nodes (no children), with no annotations, so
avoid creating the empty data structures to hold data that will likely
never arrive.
This will lower the CPU overhead a small amount (no need to call then destroy an
extra set of objects), and will chip away at any memory overhead as
well, especially on long-running requests that create many Layer objects
=> Don't create unnecessary variables in Layer#initialize

lib/scout_apm.rb, lib/scout_apm/layer.rb, lib/scout_apm/layer_children_set.rb, lib/scout_apm/layer_converters/converter_base.rb, lib/scout_apm/limited_layer.rb, lib/scout_apm/merged_layer.rb, lib/scout_apm/tracked_request.rb, test/unit/layer_children_set_test.rb, test/unit/limited_layer_test.rb
This lets us cap the number of children any given layer can accumulate,
then it starts combining them together.
The limit is per type (HTTP, ActiveRecord, View...), and currently is at
1000.   That number is arbitrary, and not based on any research.  Likely it
will change or get larger as we figure out the right balance.
The reason for this is to limit the number of Layer objects we store in ram
over the course of a request. In long running jobs in particular, the
number of layers encountered can get very very large, and even though they
are pretty small objects on their own, the weight of them can add up.  This
approach provides a safety valve to prevent our memory use going up over a
long trace.
Anything going over the limit gets bucketed into a single `HTTP/Merged`
bucket, which shows …
=> Add and wireup a LayerChildrenSet to cap the number of children for a layer

lib/scout_apm/agent.rb, lib/scout_apm/config.rb
This dumps a list of all settings and where they came from (Defaults, ConfigFile, Environment...), when debug logging is enabled.
To enable debug logging, start your application server with an environment variable `SCOUT_LOG_LEVEL=debug` or set `log_level: debug` in the appropriate section of `scout_apm.yml`.
=> Add a debug log of all config settings & where they came from

lib/scout_apm.rb, lib/scout_apm/agent.rb, lib/scout_apm/config.rb, lib/scout_apm/instruments/middleware_detailed.rb
The detailed_middleware option switches from a general measurement of
all middlewares to a per-middleware measurement. This has an additional
overhead of 10-15ms for normal requests, which is significant enough
that it isn't the default, but shouldn't be a problem to run in
production if you do need it.
=> Config option `detailed_middleware` to monitor each middleware layer

lib/scout_apm/instant/assets/xmlhttp_instrumentation.html
To prevent a "race condition" that can occur when the `setTimeout` functionality is executed after the [incorrectly] global var gets clobbered by another call to `onload`.
=> Use "var" keyword here

lib/scout_apm/agent.rb, lib/scout_apm/config.rb, lib/scout_apm/instant/middleware.rb
* Much cleaner, split into different methods.
* Safer - fallback rescue should handle most situations
* Now works with Grape endpoints that return HTML but not ActionDispatch::Response objects
=> Refactor DevTrace's middleware

lib/scout_apm/agent.rb, lib/scout_apm/instruments/action_controller_rails_3_rails4.rb, lib/scout_apm/instruments/action_view.rb
The big gotcha I had to work around here is that API & Base controllers both inherit from Metal. So if I instrument both, the code needs to be sure not to start two Controller layers.  See the specific commit messages for the mechanism I used for that (the dynamic module stuff)
=> Add automatic instrumentation of API & Metal controllers

lib/scout_apm.rb, lib/scout_apm/rack.rb, lib/scout_apm/tracked_request.rb
Usage in a minimal rack app:
require 'rubygems'
require 'bundler'
Bundler.require
ScoutApm::Rack.install!
app = Proc.new do |env|
ScoutApm::Rack.transaction("Basic", env) do
sleep 2
['200', {'Content-Type' => 'text/html'}, ['A barebones rack app.']]
end
end
run app
=> Simple Rack instrumentation

lib/scout_apm/agent.rb, lib/scout_apm/environment.rb
Background: We already mostly did this, but in a roundabout way by checking if we were loading into a web server (or a background job env). This is more direct and avoids some edge cases we've seen.
=> Don't start the agent in Rails console

lib/scout_apm/instruments/resque.rb
Also add a fallback. We shouldn't ever allow queue to be nil, even
though I don't think resque will run a job if both @queue and #queue are
missing. Always have a fallback of "unknown", so we can report smething.
This oversight of queue name was manifesting as a call to nil.downcase
when we go to process the JobRecord.
=> Also find queue of a resque job from klass.queue

lib/scout_apm/background_worker.rb
The background worker is firing its task one last time, when I don't
think it should.
The order of shutting down:
* Agent class at_exit handler fires
* Agent calls BackgroundWorker.stop (setting @keep_running = false)
* Agent calls store.write_to_layaway(force)
* Store writes any in-memory data to file
* Agent calls Thread.wakeup on BackgroundWorker & Thread.join on it.
* Background worker was likely waiting on sleep, it wakes from sleep
* It then immediately runs its task.
* Write to layaway (normal)
* Attempt to report
* Finally at_exit handler joins the thread, and finishes shutting down
I think that the step where we run the task one last time is
unnecessary, and potentially overwriting files during its layaway write.
And a report could take several seconds if our checkin server is …
=> Don't run the background worker task after being shut down

lib/scout_apm/instruments/active_record.rb
We were seeing no SQL parameters logging to our normal Rails logs and this was why!
I'd like to encourage Scout to please use ActiveRecord's instrumentation instead of overriding methods. This could just be a subscription to `sql.active_record` now instead of messing with alias method chains.
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L542-L543
=> Fix Rails 5+ SQL parameter logging

lib/scout_apm.rb, lib/scout_apm/agent.rb, lib/scout_apm/background_recorder.rb, lib/scout_apm/config.rb, lib/scout_apm/synchronous_recorder.rb, lib/scout_apm/tracked_request.rb
This allows different approaches on how to handle the TrackedRequest
object after the request is finished.
This PR adds a configuration option to allow tracing of tracked requests
in a different thread than the request itself, allowing it to get out of
the critical path of the response.
With async_recording setting:
```
Before:
Start Req --> End Req --> #record! (& process) --> Store --> Response sent
After:
Start Req --> End Req --> Response sent
--> #record! (& process) --> Store
```
The goal is that the time spent recording the details of the request is
now not in the way of returning the request.  The same amount of work is
done, just in a background thread instead of the hot-path of the
request.
=> Abstract recording approach from TrackedRequest

lib/scout_apm/utils/sql_sanitizer.rb
SQL Scrubbing is only used when we capture traces, which only happens a
handful of times per minute, so performance isn't as big a deal now as
when we initially introduced this limit. Back then, we were running sql
scrubbing eagerly on nearly every SQL statement
=> Be more generous with max sql length we're willing to scrub

lib/scout_apm/instruments/net_http.rb
When using Faraday using the default adapter (`Net::HTTP`), if `rest-client` is also installed it can cause double-counting of the number of HTTP requests. This commit ignores any children of `Net::HTTP.request` calls.
=> Ignore children of Net::HTTP instrument layers

lib/scout_apm/reporting.rb, lib/scout_apm/store.rb
Previously, if a worker got no traffic at all, we would not necessarily
create a ReportingPeriod object for that minute, which in turn would
mean we didn't collect samplers.
The result was memory usage appearing to jump up & down more than it
really was (since we were missing certain processes' readings).
Now, the store has a #tick! method to do any per-minute work, including
creating that reporting period, and reading samplers into it.
ALSO: this fixes another minor issue related to shutdown. When shutting
down, the agent called #write_to_layaway(force). This caused
double-readings of memory when called in the sequence inside of a minute:
* write_to_layaway normally
* shutdown
* write to layaway forced
=> Move creation of reporting periods, and samplers to own method

lib/scout_apm.rb, lib/scout_apm/agent.rb, lib/scout_apm/fake_store.rb, lib/scout_apm/layaway.rb, lib/scout_apm/layaway_file.rb, lib/scout_apm/tracked_request.rb
There was logic to avoid installing instruments when an app server wasn't
detected, and also separate logic to start the agent when a web request
came through. The interaction was that it would start the agent, but not
actually install instruments. So an app would report memory & cpu usage,
but not any throughput or traces.
This ensures that instruments are installed more often (when monitor=true
at least)
=> Ensure instruments are installed correctly

test/unit/logger_test.rb
If the `log/` directory does not exist, `ScoutApm::Logger` falls back to `STDOUT`. Therefore, a fresh checkout of `scout_app_ruby` fails with something like:
```
1) Failure:                                                                              
LoggerTest#test_pick_log_file_with_no_options [/home/alindeman/src/github.com/scoutapp/scout_apm_ruby/test/unit/logger_test.rb:29]:                      
--- expected                                                                
+++ actual                                                                                                                                               
@@ -1 +1 @@ …
```
=> Ensures log directory exists

lib/scout_apm/agent_context.rb, lib/scout_apm/logger.rb, lib/scout_apm/tracked_request.rb
If we don't, we may rehydrate a modified agent context from the child
process, which will include a FakeStore, and will then figure out
metrics, and then drop them.
=> Be sure to wipe & restore agent_context when using Remote agent

lib/scout_apm/tracked_request.rb
When #145 was fixed, we changed the definition of the `web?` and `job?`
methods in TrackedRequest to look at the real stack of layers, rather
than using marker booleans set by the ActionController and background
job instrumentations.
Because of that change, and caching of the values, an optimization
check in `capture_backtrace?` was always returning false, skipping
backtrace collection.
The fix is to untangle the logical `web?` call into two distinct items.
One is for recording, and is still called `web?` (and `job?`). It looks
at the layers.
Then adding a new flag, set while a request is running, that marks it as
a `real_request!`. That then is a signal to future instrumentation that
its worthwhile to enable all the various captures we do, and that we're
not wasting time.
The initial …
=> Fix recording backtraces

Gemfile
Not sure why this didn't show up as an issue until now, but this should fix the Travis build failure on Ruby 1.8.7.
=> Pins rake to 10.5 on Ruby 1.8.7

lib/scout_apm/layaway.rb, test/unit/layaway_test.rb
We had a customer with a `data_file` set to `/srv/appname/shared/tmp/scout_apm/`. The `scout_apm` part of the path was causing the `Layaway#timestamp_from_filename` used by `Layaway#delete_stale_files(older_than)` to pick up the wrong file name:
```
DEBUG : Deleting stale layaway files with timestamps: ["apm/scout_201803121007", "apm/scout_201803102318"
```
This PR changes the `match` regex used by `Layaway#timestamp_from_filename` which should fix the issue. This PR also adds a test for this case but for some reason the test is not running as expected. @cschneid or @alindeman mind taking a look at the test?
=> Change stale layaway regex, add test

lib/scout_apm/instruments/active_record.rb
Rails 5.2 factored away the `find_with_assocations` method, so a replacement needs to be found for starting instrumentation without generating a lot of false noise.
Rails 3.2 introduced a private method `exec_queries` to `ActiveRecord::Relation` that has survived through to Rails 5.2 and seems relatively stable at this point. It is a good candidate to achieve the same instrumentation goals because it is just one call earlier in the chain of the calls invoked when a query (or group of queries) is being invoked.
In Rails 3.2 through Rails 5.2, the possible call chains relevant to instrumentation look like:
* `exec_queries` -> (if eager loading) _uninstrumented methods_ -> (if cache miss) `log`
* `exec_queries` -> (if not eager loading) `find_by_sql` -> (if cache miss) `log`
Rails 3.2 …
=> Instruments early via exec_queries in Rails >= 3.2

lib/scout_apm/environment.rb, lib/scout_apm/instruments/active_record.rb
We've seen in #114 and #186 that `alias_method_chain` style chaining and `prepend` do not mix well. Infinite loops and blown stacks often result.
This PR proposes the first steps toward supporting `Module#prepend` in instruments by `prepend`ing a module to `ActiveRecord::Relation` if `prepend` is supported. It should resolve #186.
`ActiveRecord::Relation` is a good candidate for prepending because it is a `Class` that we are prepending directly to. This is a pretty straightforward case without any edge cases that I can see.
I try to keep the duplication to a minimum, even though several new conditionals are introduced. I'm interested in how this code strikes people, and if you think there are better options.
Relates to #178 as well, though in #178 we tackle `Tracer`, rather than a …
=> Supports prepending exec_queries

CHANGELOG.markdown, lib/scout_apm/background_job_integrations/delayed_job.rb
If a DelayedJob job is queued for future execution (`Job.delay.deliver(run_at: 5.minutes.from_now)` or via ActiveJob `Job.set(wait: 5.minutes).perform_later`), the queue latency should be calculated from the time the job was expected to run, instead of when it was created.
DelayedJob sets `run_at` to the current time if no delay is specified, so this logic should still work correctly for jobs scheduled for immediate execution.
Fixes #189
=> Calculates queue latency correctly for scheduled jobs

lib/scout_apm/instruments/active_record.rb
Potential fix for #211 
Datadog mutates the `:payload` key in the ActiveSupport instrumentation used by both Scout and Datadog, resulting in Scout encountering unexpected data, which it then annotates to layer and eventually attempts to dump to the layaway file. Dumping fails due to the annotations containing un-marshalable `Thread::Mutex`es.
This proposes being stricter in what keys to copy from ActiveRecord instrumentation payloads and solves the problem locally for me. In addition to opening up compatibility with Datadog, it's arguably more future-proof to other types of data being added here that we may not care about.
I'm on Rails 4.2, so it may be that later Rails versions have already added keys here that Scout APM finds useable, in which case this would need to be revised.
If this …
=> Only annotate layer with known payload

lib/scout_apm.rb, lib/scout_apm/store.rb
Issue #205 has a situation where the @reporting_periods hash was
updated during iteration, causing an exception. I think that the issue
is that we added a new StoreReportingPeriod during write_to_layaway
running. So we were looping and then added a new item, causing the
exception.
This wraps both in correct locks. But that was difficult with a mutex,
since you can't reobtain an already taken mutex. Monitor is the same,
but does allow that reentrant behavior, so this switches over to it.
=> Use Monitor in Store, and add a locked section

CHANGELOG.markdown, lib/scout_apm/layer_converters/database_converter.rb, lib/scout_apm/utils/active_record_metric_name.rb, test/unit/utils/active_record_metric_name_test.rb
`BEGIN` and `COMMIT` can take significant time. This identifies these queries in the metric name.
Currently, these are named `SQL/other`, which is our fallback when we're unable to come up with a label for an SQL query.
=> ActiveRecord query naming enhancements

lib/scout_apm.rb, lib/scout_apm/background_job_integrations/shoryuken.rb, lib/scout_apm/environment.rb
If Shoryuken is launched as part of Rails, it will be detected automatically.
If Shoryuken is launched separately, as a standalone worker, an initializer is
required to start the agent:
```ruby
Shoryuken.configure_server do |config|
config.on(:startup) do
require 'scout_apm'
ScoutApm::Agent.install
ScoutApm::Agent.start
end
end
```
Closes #195
=> Initial Shoryuken support

lib/scout_apm/framework_integrations/rails_2.rb, lib/scout_apm/framework_integrations/rails_3_or_4.rb
Hey!
At Streetbees we have a custom Sinatra API and one of the gems we use is defining the `Rails` module. Because of that, both these framework integrations would try to be loaded. That leads to errors because the `Rails` gem is not actually being installed.
After digging a bit into the code I found the `Rails::VERSION` is not defined on our app and, doing that check allows us to integrate with Scout.
Couldn't find any existing tests for `ScoutApm::FrameworkIntegrations`. If this change makes sense for you, can you show me where to add them?
Thanks!
=> Look also for ::Rails::VERSION to check if Rails present

lib/scout_apm/background_job_integrations/resque.rb, lib/scout_apm/config.rb
Allows a user to override the default starting of the WEBrick server in the
Resque master process.
This will prevent the instrumentation from working unless the server is
started explicitly elsewhere.
=> Add start_resque_server_instrument configuration

lib/scout_apm/config.rb, lib/scout_apm/git_revision.rb
For more flexibility, we can now read a user-provided SHA from the configuration system, rather than directly from the ENV. This allows a user to set the value in the YAML.
=> Read revision_sha from config (in addition to ENV)

lib/scout_apm/config.rb
Closes #233 
From issue #233:
Currently, 'compress_payload' is not in coercion list.
So it's getting the literal string "false" as the value, which in ruby is a true value, so the if succeeds.
=> Add 'compress_payload' to coercion list

.travis.yml
Both RubyGems and Bundler have moved past Ruby versions 2.2 and older. They
don't work at all, and error out when installed on those older versions.
A more complete solution would be a conditional updating based on Ruby version,
but since we only barely use the features of RubyGems and Bundler, I didn't
think it was worth the hassle.
=> Fix Travis Builds by restricting to older version of Gem & Bundler

lib/scout_apm/instruments/action_view.rb
A customer ran into an incompatibility between Scout and the `jb` gem in
ActionView. There's no reason not to use prepend whenever we can, so this
changes the check from being restricted to Rails 6+ and just opens it up to all
versions of Ruby that supports prepend, no matter the Rails version.
=> Use view instrument module#prepend whenever possible

README.markdown
Without setting the test env, we get an error:
```
Couldn't find configuration in app/config/scout_apm.yml for environment: test.
```
=> Add monitor false for test env

lib/scout_apm.rb, lib/scout_apm/background_job_integrations/que.rb, lib/scout_apm/environment.rb
The commit adds support for Que v0.14.3. Que 1.0.0 is going to have significant changes especially relating to ActiveJob.
I have tested it locally and it appears to be working in my account. If you like it and accept it. I can deploy it on a few applications.
Please let me know if I missed anything!
=> add background job support for que v0.14.3

lib/scout_apm/layer_converters/trace_converter.rb
Fixes #267 by not processing limited layers.
Note that the exception reported in #267 only hits this issue if `DEFAULT_UNIQUE_CUTOFF` > `MAX_SPANS`. This provides additional protection. 
This is phase 2 mentioned in Slack:
=> Gracefully don't process LimitedLayer objects for a Detailed Trace

.gitignore, .travis.yml, gems/README.md, gems/minimum.gemfile, gems/octoshark.gemfile, gems/rails3.gemfile, gems/rails4.gemfile, gems/rails5.gemfile, gems/rails6.gemfile, lib/scout_apm/instruments/active_record.rb, scout_apm.gemspec, test/test_helper.rb, test/tmp/README.md, test/unit/instruments/active_record_instruments_test.rb, test/unit/instruments/active_record_test.rb
This PR implement a quick fix and regression tests to sort out https://github.com/scoutapp/scout_apm_ruby/issues/217
I've updated the travis test matrix in order to expand our ability to test combinations of different gems using the `gems/*.gemfile` approach which I've used in the past, and implemented a very basic test case for ActiveRecord.
Finally, I discussed the best way to fix this with @cschneid and we decided that a quick fix was preferable, and the mid-term solution is to deprecate Ruby < 2.1 going forward, but that requires a bit more effort. So, this PR is good to be merged IMHO, and paves the way for 3.x.
See also https://github.com/scoutapp/scout_apm_ruby/pull/270
=> ActiveRecord quick fix

lib/scout_apm/detailed_trace.rb
Rails 2.3 as_json does not recurse into objects. We were calling `as_json` on arrays of `DetailedTraceSpan`s which returned an array of `#DetailedTracesSpan` strings. Instead of calling as_json on array of detailed trace spans, map over them and call as_json on each.
=> Legacy as_json fix for DetailedTrace spans

Gemfile, lib/scout_apm/agent_context.rb, lib/scout_apm/auto_instrument/instruction_sequence.rb, lib/scout_apm/auto_instrument/layer.rb, lib/scout_apm/auto_instrument/rails.rb, lib/scout_apm/config.rb, lib/scout_apm/instant/middleware.rb, lib/scout_apm/layer.rb, lib/scout_apm/periodic_work.rb, lib/scout_apm/request_histograms.rb, lib/scout_apm/tracked_request.rb, test/unit/auto_instrument/assignments-instrumented.rb, test/unit/auto_instrument/controller-instrumented.rb, test/unit/auto_instrument_test.rb
Instrumenting many insignificant layers adds overhead. These insignificant layers are unlikely to be areas a developer will optimize. This adds a persistant Histogram that logs a count of total autoinstrumented layers and the percent significant per-file name.
In the example output below, `application_controller.rb` is potentially adding overhead as it is tracking a large number of layers and a low percentage (8%) are significant. This file can be excluded from autoinstruments via the new `autoinstruments` config option: `auto_instruments_ignore: ['application_controller']`.
```
[09/19/19 10:55:36 -0600 Dereks-MacBook-Pro.local (66345)] DEBUG : AutoInstrument Layer Histograms: {"/Users/dlite/projects/scout/apm/app/controllers/application_controller.rb"=>
{:total=>1774, …
```
=> Logging autoinstrument layers that are significant/insignicant + ignoring files

lib/scout_apm/periodic_work.rb, lib/scout_apm/request_histograms.rb, test/unit/request_histograms_test.rb
A customer ran into an issue with log_layer_histograms in PeriodicWork
raising an exception (and hitting the rescue in BackgroundWorker,
preventing data from being reported). After some investigation it came
to light that the customer didn't have ActiveSupport in their app (a
background job worker), and so Hash#as_json wasn't being monkey patched
in.
This changes a few things:
* Renames some methods & variables in periodic work to be more clear
about what everything is for
* Only attempt to log autoinstrument timings if autoinstruments is actually configured
* Changes the as_json call in RequestHistograms to work outside AS (also
a test)
* devolve `inject` call to use manual summing, so it works on older
rubies.
=> Prevent potential exceptions in PeriodicWork while doing logging

lib/scout_apm/instruments/http.rb
Fixes https://github.com/scoutapp/scout_apm_ruby/issues/258
This requires testing. I'm not aware of how this should be done, but how about something like this?
```ruby
def test_http_instrumentation
context = ScoutApm::TestContext.new
ScoutApm::Instruments::HTTP.install(context)
events = context.track_events do
HTTP.get("http://www.google.com/search?q=kittens")
end
assert_equal events, [
["HTTP", "get", "http://www.google.com/search"]
]
end
```
cc @dlanderson @cschneid
=> Add HTTP instrumentation.

lib/scout_apm.rb, lib/scout_apm/layaway_file.rb, lib/scout_apm/layer_children_set.rb, lib/scout_apm/remote/message.rb, lib/scout_apm/serializers/app_server_load_serializer.rb, lib/scout_apm/serializers/directive_serializer.rb, lib/scout_apm/utils/marshal_logging.rb, test/unit/layer_children_set_test.rb
This was exposed in the Resque instruments, after collecting data for a job it
ships it via a loopback HTTP server, with Marshal.dump as the serialization.
LimitedLayer had a Hash.new, with a default proc, causing the serialization to fail.
This PR also adds much better debug logging in the face of Marshal.dump errors, digging
into exactly what failed to dump, rather than the default ¯\\_(ツ)_/¯ from Ruby.
=> Fixes Marshal.dump error in LimitedLayer

lib/scout_apm.rb, lib/scout_apm/background_job_integrations/legacy_sneakers.rb, lib/scout_apm/background_job_integrations/sneakers.rb
This is different than other BackgroundJobIntegrations and must be prepended
manually in each job to be instrumented.
```
class MyWorker
prepend ScoutApm::BackgroundJobIntegrations::LegacySneakers
def work(msg)
...
end
end
```
=> Add LegacySneakers module to prepend in workers for Sneakers 2.5

lib/scout_apm/extensions/transaction_callback_payload.rb
* In a TrackedRequest, the `queue_time` is present, but the `queue` is
`nil` (because we don't know what the queue is, just that we've been
given a queue time via a request header)
=> Fix typo when calling `queue_time_ms`

lib/scout_apm/instruments/action_controller_rails_3_rails4.rb
The instrumentation referenced ActionController::Base at boot, which triggered a deprecation warning in the Rails 6 autoloader. This now wraps it in the proper ActiveSupport.on_load call.
=> Fix Rails 6 Deprecation Warning 

lib/scout_apm/instruments/action_view.rb
This fixes #335, but will need to be revisited for the next version of Rails that's released, since the templating logic has changed again on master.
=> Fix partial naming on early Rails 6 versions

lib/scout_apm/background_job_integrations/sidekiq.rb
Currently on the (yet-unreleased, on master branch) Sidekiq 6.1, the Processor#initialize method signature has changed to add a new options argument. We don't care about the argument at all, and just want to be sure Scout starts at boot time, so pass through whatever is handed to us via `*args` instead of having any knowledge of the signature.
I have verified that Sidekiq now boots against both 6.1 and the released 6.0.7 versions. I have not done full path testing of Sidekiq 6.1 to verify all of our other instruments work as expected, but we rely on standard sidekiq middleware and I doubt that API has changed drastically.
Fixes #340
=> Fix Sidekiq 6.1.0's changed signature on Processor#initialize

lib/scout_apm/instruments/action_controller_rails_3_rails4.rb
Scout captures the incoming URI and stores it for viewing on traces. There
are 2 pre-existing built in security modes, one that captures the whole
thing, and one that trims off any query params (?foo=bar)
But some users have more advanced needs for manipulating the URI before
capturing. Typically these involve times where personally identifiable
info gets put into the URL itself. The motivating example of this is
a url that looks something like /users/chris@scoutapm.com/dashboard.
The customer with that URL doesn't want to send all of their customer's
email addresses up, but also doesn't want to give up uri capturing
generally.
The new API is to override the `scout_transaction_uri` function in
the controller, returning a string with the modified uri. To get the
built in version, call …
=> User override of captured URI on Controllers

lib/scout_apm/error_service/error_record.rb
Remove many more keys from ENV that are related to raw URL data (potential PII leak), and security (should never leave the host system)
=> Remove many more keys from ENV captured by errors

lib/scout_apm/serializers/payload_serializer_to_json.rb, test/unit/serializers/payload_serializer_test.rb
Needs some more testing. This should fix a reported issue with escaping real backslashes in the payload. In the reported case, it was in the middle of some SQL, where the customer was storing escaped JSON as a string - the escaping we had previously failed to generate valid JSON.
Note, this entire json serializer should be removed, and we can begin relying on Ruby's built-in JSON library once we bump the minimum version to Ruby 2.1+. We only have it to avoid an extra dependency in Ruby 1.8.7.
=> Fix escaping real backslashes in payload json

lib/scout_apm/instruments/active_record.rb
This pull request resolves three deprecation warnings seen when using the latest version of scout_apm (v2.6.9) with Ruby 2.7.1.
4c7ac9f94fd99b1e94fdeb1b09b41d7099b9e19c resolves the specific warning cited in https://github.com/scoutapp/scout_apm_ruby/issues/319. This warning is seen when using `ActiveRecord::Querying.find_by_sql`:
gems/scout_apm-2.6.9/lib/scout_apm/instruments/active_record.rb:333: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
gems/activerecord-6.0.3.3/lib/active_record/querying.rb:45: warning: The called method `find_by_sql_without_scout_instruments' is defined here
1aa5f92e1a787da122167fcba425c44f59ebe440 resolves the following warnings seen using `ActiveRecord::Persistence#save` and …
=> Fix a handful of Ruby 2.7 deprecation warnings

lib/scout_apm/utils/sql_sanitizer_regex.rb, test/unit/sql_sanitizer_test.rb
Multiline postgres sql was avoiding some of the sanitization we have. This is rare since AR doesn't create that kind of SQL itself normally. 
Also added a simple test for mysql sql as well.
=> Handle multiline psql sql sanitizing

.github/workflows/test.yml, .rubocop.yml, scout_apm.gemspec
This replicates our existing travis ci build here in Github actions. Travis has been slower & slower to run tests on open source repos, and github is much faster.
=> GitHub Actions CI

lib/scout_apm/instruments/action_view.rb
But don't do that in the PartialRenderer instrument, which has different interface that has locals as an instance var, not passed to the method. (Rails 6.0.3, Rails 4.2)
=> Pass kwargs to render_partial instrument in TemplateRenderer (for locals)

lib/scout_apm/serializers/payload_serializer_to_json.rb
This hack, added on Oct 2020 (#360) was a way to fix a use case related to Regexp in ruby 1.8.7
Since Scout APM 4.0.0 (Nov 2020), the gem only support ruby ~> 2.1 (#270).
Is not longer possible to use ruby 1.8.7, the hack can be safely removed.
https://github.com/scoutapp/scout_apm_ruby/pull/360
https://github.com/scoutapp/scout_apm_ruby/pull/270
=> Removing Hack for Regexp supporting ruby 1.8.7

lib/scout_apm/framework_integrations/rails_3_or_4.rb
Prior to this change, the first interaction with the database would emit the following deprecation warning with Rails 6.1:
> DEPRECATION WARNING: connection_config is deprecated and will be removed from Rails 6.2 (Use connection_db_config instead)
The deprecation was introduced in https://github.com/rails/rails/pull/38005 and includes the following [release notes](https://github.com/rails/rails/pull/38005/files#diff-353f4f101b1bb04938d761b6e29c88e0f147084e9e276854a77ae5d9a9a3b2a8):
> The `connection_config` method has been deprecated, please use `connection_db_config` instead which will return a `DatabaseConfigurations::DatabaseConfig` instead of a `Hash`.
With the changes in the pull request, Scout first attempts to use `connection_db_config`. If unsuccessful, Scout falls back to the …
=> Resolve Rails 6.1 deprecation warning re: connection_config

lib/scout_apm/agent/preconditions.rb
In certain cases background job integrations will be stand alone without an accompanying app server. We want to start the agent in these cases
=> Fix deferring of agent if app server or background integration exists

lib/scout_apm/instruments/typhoeus.rb
Set up desc on new layers before starting the layer rather than setting it on the current layer after start_layer.
To fix : https://github.com/scoutapp/scout_apm_ruby/issues/391
This means that if the current layer isn't the one we just tried to start then the desc isn't set on a layer we weren't expecting.
I haven't managed to reproduce this in a test (it's not clear to me the best way to test layering integration of different instrumentation).
Reproducing in a separate application was achieved by an active record callback calling Typhoeus (through elasticsearch) and then further active record operations taking place.
=> Set up desc on new layers before starting the layer

lib/scout_apm/instruments/active_record.rb
Should fix: https://github.com/scoutapp/scout_apm_ruby/issues/393
Rails edge changed the signature of `#log`, it now includes a keyword arg (see https://github.com/rails/rails/pull/40037)
The only proper way to blind delegate keyword args across versions is to use ruby2_keywords, see https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html for details.
=> Improve blind delegation of ActiveRecordInstruments#log

lib/scout_apm/background_job_integrations/shoryuken.rb
This resolves the following issue that we bumped into when using scout_apm in conjunction with shoryuken.
```ruby
uninitialized constant Shoryuken::Processor::Celluloid
```
```
/usr/local/rvm/gems/ruby-2.4.5/gems/shoryuken-2.0.2/lib/shoryuken/processor.rb:5:in `<class:Processor>'
/usr/local/rvm/gems/ruby-2.4.5/gems/shoryuken-2.0.2/lib/shoryuken/processor.rb:4:in `<module:Shoryuken>'
/usr/local/rvm/gems/ruby-2.4.5/gems/shoryuken-2.0.2/lib/shoryuken/processor.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.4.5/gems/scout_apm-2.6.6/lib/scout_apm/background_job_integrations/shoryuken.rb:40:in install_processor'
/usr/local/rvm/gems/ruby-2.4.5/gems/scout_apm-2.6.6/lib/scout_apm/background_job_integrations/shoryuken.rb:21:in `install'
```
=> preload celluloid before shoryken processor

lib/scout_apm/instant/middleware.rb, lib/scout_apm/instruments/elasticsearch.rb, lib/scout_apm/instruments/sinatra.rb, lib/scout_apm/utils/sql_sanitizer.rb, test/unit/sql_sanitizer_test.rb
I was running scout in an environment where strings are frozen by default (using `RUBYOPT="--enable=frozen-string-literal"`) and Scout started raising exceptions. 
The magic comments allow it to run in this environment, without affecting a "typical" setup, or changing code.  
Before this PR, running tests using `RUBYOPT="--enable=frozen-string-literal rake` on `scout_apm_ruby` fails. After, it passes.
=> Add magic comment frozen_string_literal: false to files where strings are modified

lib/scout_apm/logger.rb
I have not tested this change, but just to open up the discussion. 
Maybe Scout should not block rails from booting if it cannot write to the default log folder.
Thanks
setting the ENV var `SCOUT_LOG_FILE_PATH` to `stdout` prevents this problem, but by default, it should not crash
```
passenger.log-[ 2021-09-03 02:14:38.5897 10450/7f6fc79a2700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /var/app/current: An error occured while starting up the preloader.
passenger.log-  Error ID: 997f79e2
passenger.log-  Error details saved to: /tmp/passenger-error-svSwzi.html
passenger.log:  Message from application: Permission denied @ rb_sysopen - /var/app/current/log/scout_apm.log (Errno::EACCES)
passenger.log-  /opt/rubies/ruby-2.6.8/lib/ruby/2.6.0/logger.rb:744:in …
```
=> Do not crash the app if Scout can't log to a file

lib/scout_apm/tracked_request.rb
Rails live can apparently cause mismatches of layers, and close out parent layers before we get a chance to add their children.
This change makes sure we only fetch the parent layer once, instead of the previous one checking `@layers` twice.
=> Check that the parent layer exists, avoiding a race condition induced exception

CHANGELOG.markdown, lib/scout_apm/framework_integrations/rails_3_or_4.rb
Rails 6 updated the value of `ActiveRecord::Base.configurations` to return an object instead of a plain hash. See https://github.com/rails/rails/pull/33637 for more info.
To avoid deprecation warning when accessing the object using `[]`, we instead call `to_h` to get a plain hash like we expected before the Rails 6 change. The `to_h` call is the recommended way to get these configs in a backward compatible way.
=> Call to_h on ActiveRecord::Base.configurations

CHANGELOG.markdown, lib/scout_apm/config.rb
Due to https://github.com/ruby/psych/pull/487 making YAML loads strict by default, when someone is running with Psych > 4 and Scout attempts to load `config/scout_apm.yml` with references, an exception is raised, caught, and logged, but the config is not loaded from the file.
Similar to the rails change https://github.com/rails/rails/pull/42257, we can consider configuration files as trusted.  This change reads the yml file with `unsafe_load` if available.
=> Allow using `YAML.unsafe_load` when reading scout_apm.yml

.github/workflows/test.yml, gems/instruments.gemfile, lib/scout_apm/config.rb, lib/scout_apm/instrument_manager.rb, lib/scout_apm/instruments/action_controller_rails_2.rb, lib/scout_apm/instruments/action_controller_rails_3_rails4.rb, lib/scout_apm/instruments/action_view.rb, lib/scout_apm/instruments/active_record.rb, lib/scout_apm/instruments/elasticsearch.rb, lib/scout_apm/instruments/grape.rb, lib/scout_apm/instruments/http.rb, lib/scout_apm/instruments/http_client.rb, lib/scout_apm/instruments/influxdb.rb, lib/scout_apm/instruments/memcached.rb, lib/scout_apm/instruments/middleware_detailed.rb, lib/scout_apm/instruments/middleware_summary.rb, lib/scout_apm/instruments/mongoid.rb, lib/scout_apm/instruments/moped.rb, lib/scout_apm/instruments/net_http.rb, lib/scout_apm/instruments/rails_router.rb, lib/scout_apm/instruments/redis.rb, lib/scout_apm/instruments/sinatra.rb, lib/scout_apm/instruments/typhoeus.rb, test/unit/instruments/active_record_test.rb, test/unit/instruments/http_client_test.rb, test/unit/instruments/http_test.rb, test/unit/instruments/moped_test.rb, test/unit/instruments/net_http_test.rb, test/unit/instruments/redis_test.rb, test/unit/instruments/typhoeus_test.rb
For many of our instruments, we still use `Module#alias_method` to monkeypatch specific methods to gather telemetry. The more modern approach is to use `Module#prepend`, which many other gems now use as default.
Moving from `alias_method` to `prepend` has caused major headaches for nearly all gems which made the switch, despite making the change in a major version semantic version bump. In order to allow a less disruptive upgrade path, Scout will continue to use `alias_method` as the default, but with available configuration option to move either all instrumentation to `prepend`, or selectively move instrumentation to `prepend`.
We will consider making the `prepend` instrumentation default after this configurable option has been released for a sufficient amount of time.
This is the …
=> Initial commit for adding prepend in addition to alias_method

lib/scout_apm/instruments/http_client.rb
looks like a typo for me
without this fix:
```ruby
> require 'scout_apm'; require 'scout_instruments'; HTTPClient.new.request(:get, 'http://e1.ru/')
Traceback (most recent call last):
16: from /usr/lib/ruby/2.7.0/set.rb:328:in `each'
15: from /usr/lib/ruby/2.7.0/set.rb:328:in `each_key'
14: from /bundle/2.7-deb/ruby/2.7.0/gems/scout_apm-5.3.0/lib/scout_apm/layer_children_set.rb:67:in `block (2 levels) in each'
13: from /bundle/2.7-deb/ruby/2.7.0/gems/scout_apm-5.3.0/lib/scout_apm/layer_converters/depth_first_walker.rb:36:in `block in walk'
12: from /bundle/2.7-deb/ruby/2.7.0/gems/scout_apm-5.3.0/lib/scout_apm/layer_converters/depth_first_walker.rb:33:in `walk'
11: from /bundle/2.7-deb/ruby/2.7.0/gems/scout_apm-5.3.0/lib/scout_apm/layer_children_set.rb:65:in `each'
10: from …
```
=> Fix typo in "request" method of HTTP::Client

lib/scout_apm/server_integrations/puma.rb
This fixes issue #253, which describes a bug causing Puma `on_worker_boot` callbacks to fire *twice* per definition when the `scout_apm` gem is included in the same Rails application. We discovered this issue (and then stumbled upon issue #253) while trying to add some statistics logging in our own Puma plugin, via a tread spawned in `on_worker_boot`. We were able to diagnose this as being an issue specifically with the `on_worker_boot` *callbacks* being fired twice (they were not *defined* or loaded twice), and it occurs only when `scout_apm` is included in the application and active via `monitor: true` in `config/scout_apm.yml`.
This can be replicated by including both `puma` and `scout_apm` in a Rails application, setting `monitor: true` for your environment in `config/scout_apm.yml`, …
=> Work around Puma config option issue causing duplicate before_worker_boot invocations when scout_apm is loaded

.github/workflows/test.yml
Quoting '3.0' is necessary to avoid truncation to '3'.  If truncated to '3', then the latest Ruby 3 (currently Ruby 3.2.0) is loaded, which is not the intended behavior.
=> Adds Ruby 3.1 and 3.2. Quotes 3.0 to avoid truncation. Updates action versions

lib/scout_apm/slow_request_policy.rb
I was noticing that I'm not getting a lot of traces for high-traffic endpoints, and I think this might be why? I think this PercentPolicy got lost in a refactor, and PercentilePolicy was listed twice instead. It does look like [PercentPolicy](https://github.com/scoutapp/scout_apm_ruby/blob/master/lib/scout_apm/slow_policy/percent_policy.rb) is the rule that helps track high traffic endpoints.
ref: https://github.com/scoutapp/scout_apm_ruby/commit/026f04ea77dde448da9d82b7456abbd849f5f315
=> Add back PercentPolicy to SlowRequestPolicy

lib/scout_apm/instruments/active_record.rb, test/test_helper.rb, test/unit/environment_test.rb, test/unit/instruments/active_record_test.rb
I have an initializer with this config in my Rails 6 app:
```ruby
Rails.application.config.active_record.belongs_to_required_by_default = false
```
After adding the `scout_apm_ruby` to my project, this config started not loading, which broke some features in my app. After investigating, I found that `scout_apm_ruby` was starting `ActiveRecord` without my config, this is happening because `install_via_after_initialize?` never returns true when Rails version is different from 3, which is a bug since all Rails versions above 3 can respond to `configuration` as well.
In this PR I fix this bug and add some tests to avoid regression.
=> Fix: call `add_instruments` after rails initialization when rails version is >= 3

lib/scout_apm/layer_converters/external_service_converter.rb
Replaces `.blank?` and removes the need for ActiveSupport.
Closes #467
=> Remove use of .blank? in ES converter

lib/scout_apm/app_server_load.rb
I recently upgraded my Rails app to 7.1, and am getting a lot of the following in my logs:
```
DEPRECATION WARNING: Calling `ActiveRecord::Base.clear_active_connections! is deprecated. Please call the method directly on the connection handler; for example: `ActiveRecord::Base.connection_handler.clear_active_connections!`. (called from clear_active_connections! at /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.1/lib/active_record/connection_handling.rb:323)
```
Adding some extra debugging in active_record/connection_handling.rb pointed at lib/scout_apm/app_server_load.rb:54 being the _actual_ callsite in question.
I'm not sure how backward compatible this change is (or how old of Rails is supported by Scout) but this change does clear the …
=> Fix deprecation warning in Rails 7.1

lib/scout_apm/auto_instrument/rails.rb, scout_apm.gemspec, test/unit/auto_instrument/hash_shorthand_controller-instrumented.rb, test/unit/auto_instrument/hash_shorthand_controller.rb, test/unit/auto_instrument_test.rb
We get a `SyntaxError` when instrumenting hashes with [Ruby 3.1 hash shorthand syntax](https://rubyreferences.github.io/rubychanges/3.1.html#values-in-hash-literals-and-keyword-arguments-can-be-omitted) in controllers.
Fixes #484
Fixes #445
Add a `on_hash` method that does the instrumentation correctly. 
@jrothrock - would you be the right person to ask for a review? Do let me know if there's a cleaner way to do this.
I've added test cases.
@natematykiewicz - if you would like to, you may test this with your app.
=> Fix SyntaxError when instrumenting hash with shorthand

lib/scout_apm/auto_instrument/rails.rb, test/unit/auto_instrument/hash_shorthand_controller-instrumented.rb, test/unit/auto_instrument/hash_shorthand_controller.rb
@jrothrock @natematykiewicz - I missed an edge case in #486
The `replace` action in `on_hash` should ideally run only for the case where the Ruby 3.1 hash shorthand syntax is used. If the `value_node` takes in an argument, we can be sure it's not the shorthand syntax case. This PR adds a check for that: 
```rb
value_node.children.size == 2
```
Without the change, `params["timestamp"]` gets dropped:
```rb
nested_call: ::ScoutApm::AutoInstrument(\"nested_call: nested_call(params[\\\"timestamp\\\"])\",[\"ROOT/test/unit/auto_instrument/hash_shorthand_controller.rb:15:in `hash'\"]){nested_call}
nested_call: ::ScoutApm::AutoInstrument(\"nested_call(params[\\\"timestamp\\\"])\",[\"ROOT/test/unit/auto_instrument/hash_shorthand_controller.rb:15:in `hash'\"]){nested_call(params[\"timestamp\"])}
``` …
=> Fix nested_call edge case

README.markdown, scout_apm.gemspec
If you're on Ruby 3 and  version 3.x of the `parser`gem, when you upgrade the `scout_apm` gem to 5.3.6, you will no longer be able to `bundle install`. Sample error:
```
Could not find compatible versions
Because scout_apm >= 5.3.6 depends on parser ~> 2.6
and Gemfile depends on scout_apm = 5.3.6,
parser ~> 2.6 is required.
So, because Gemfile depends on parser ~> 3.3.0,
version solving has failed.
```
It looks like `gemspecs` are not evaluated dynamically on your local machine, but when the gem is published:
```
> gem dependency scout_apm -v 5.3.6 --remote
Gem scout_apm-5.3.6
activerecord (>= 0, development)
activesupport (>= 0, development)
addressable (>= 0, development)
guard (>= 0, development)
guard-minitest (>= 0, development)
m (>= 0, development)
minitest (>= 0, development) …
```
=> Fix parser dependency

lib/scout_apm/layer_converters/request_queue_time_converter.rb
With the use of libraries such as Stimulus Reflex, which under the hood utilize Turbo Streams, we can run into issues where the queue times that we report are very inaccurate.
They appear to have the same queue time header/timestamp as when the connection was first created, and is not changed for subsequent data sent over the websocket. This leads to an ever growing queue time as long as the connection isn't terminated.
=> Don't capture queue time for websocket requests

.github/workflows/test.yml, gems/sqlite3-1.3.gemfile, scout_apm.gemspec
- Force lower version for older rubies. This is blunt, but should I don't believe it should introduce any new problems for anyone.
=> Handle sqlite3 update

lib/scout_apm.rb, lib/scout_apm/background_job_integrations/good_job.rb, lib/scout_apm/environment.rb
Add GoodJob Integration
Since this GoodJob integration is utilizing the around_perform action (like the `que` integration), you can likely reuse this integration for SolidQueue as well.
=> Good job Integration

CHANGELOG.markdown, lib/scout_apm/instruments/grape.rb
While there is still an unknown issue getting the name for some `grape` endpoints, this at least resolves the undeclared `logger` variable, which will allow capturing the true issue.
I was unable to reproduce the name issue in my (relatively naive) testing.
Closes #510
=> Fix: Undefined logger in grape instruments

.github/workflows/test.yml, gems/sqlite3-v2.gemfile
Enhance CI configuration by adding sqlite3 gemfile for Ruby 3.2/3.3 in test matrix
🤷 Sorry, I have no idea why this change has an impact on the old failing ruby tests…
=> fix failing test with ruby 3.2 and 3.3

lib/scout_apm/utils/installed_gems.rb
- fix deprecation warning when starting `rails server`
- `[DEPRECATED] Bundler.rubygems.all_specs has been removed in favor of Bundler.rubygems.installed_specs`
- reproducible with ruby v3.3.3+ (and new minimum required bundler v2.5.11, rubygems v3.5.11 versions)
- https://github.com/rubygems/rubygems/pull/7673
Fixes #513 
/cc @mpvosseller
=> fix deprecation warning Bundler.rubygems.all_specs

CHANGELOG.markdown, lib/scout_apm/agent.rb, lib/scout_apm/background_job_integrations/resque.rb, lib/scout_apm/instruments/resque.rb
- Inject ourselves into `Resque::Job`'s `payload_class` method upon initial setup so we don't rely on `after_fork`, which doesn't execute when `FORK_PER_JOB=false`. 
- Conditionally `become_remote_client` in instrumentation just like we `start_remote_server` based on `start_resque_server_instrument` config value. Also skip remote client if `FORK_PER_JOB=false`.
-  if `FORK_PER_JOB=false`, the remote server/client recording is unnecessary and actually (silently) breaks it.
=> Instrument resque without forking

lib/scout_apm/git_revision.rb, test/unit/git_revision_test.rb
With Rails 8, Kamal is the preconfigured way to deploy applications. According to the [documentation](https://kamal-deploy.org/docs/hooks/overview/), the deployed SHA can be determined from the KAMAL_VERSION environment variable.
I've also improved testing on this class.
Thanks!
=> Add support for Kamal deployments

lib/scout_apm/config.rb, lib/scout_apm/error_service/error_record.rb, lib/scout_apm/error_service/payload.rb, test/unit/error_service/error_buffer_test.rb, test/unit/error_test.rb
Updates the capturing of the environment for error records to be opt in as opposed to opt out with a few HTTP headers being automatically captured.
=> Filter env for error records
