scoutapp/scout_apm_ruby

- lib/scout_apm/instruments/http_client.rb
Add support for using URI urls instead of only strings. Will get tools like Savon / httpi to work.
> Add support for URI urls

- lib/scout_apm/config.rb
- lib/scout_apm/reporter.rb
Primarily used for features in development.
> Provides a config option for direct_host (bypassing pipeline)

- lib/scout_apm/instant/middleware.rb
* info & debug to help troubleshoot DevTrace
* report on JSON calls even if they weren't flagged as AJAX by the browser
> DevTrace improvements (mostly logging)

- CHANGELOG.markdown
- lib/scout_apm/background_job_integrations/sidekiq.rb
- lib/scout_apm/context.rb
- lib/scout_apm/tracked_request.rb
- lib/scout_apm/version.rb
- scout_apm.gemspec
- test/test_helper.rb
- test/unit/background_job_integrations/sidekiq_test.rb
- test/unit/context_test.rb
This merges together the following branches:
* https://github.com/scoutapp/scout_apm_ruby/tree/ignore-children-counter (Need to confirm working)
* https://github.com/scoutapp/scout_apm_ruby/tree/context_noise
* https://github.com/scoutapp/scout_apm_ruby/tree/sidekiq-robustness
...into a release candidate for 2.1.3.
What's left:
* Updating the version
* Updating the CHANGELOG
This should also be merged into the ScoutProf branch of the agent after release.
> Release Candidate - 2.1.3

- lib/scout_apm/agent.rb
- lib/scout_apm/background_job_integrations/sidekiq.rb
- scout_apm.gemspec
- test/test_helper.rb
- test/unit/background_job_integrations/sidekiq_test.rb
Also adds a bunch of tests, and the Mocha mocking library
> Rework sidekiq instrumentation to be more rubust against odd situations

- lib/scout_apm/tracked_request.rb
This allows arbitrarily deep nesting of inner children, which came up in
our ActiveRecord instrumentation (find_by_sql can end up calling itself)
> Use a counter for ignore_children! rather than a boolean

- lib/scout_apm/instruments/mongoid.rb
Mongoid 5 requires Mongo ~> 2.1. In development, we tested against 2.3
(current), but a customer ran into an issue where 2.1 was causing
issues.  After investigation, I found that between Mongo gem version 2.1
and 2.3, the name of the accessor that stores the active filters was
changed. This change is meant to accomodate both newer & older form.
> Fix incompatibility with Mongo gem 2.1

- lib/scout_apm/background_job_integrations/delayed_job.rb
We previously used `job.name` as the name of a DJ job being run, but that can be confused by various things, most notably, when the job overrides `display_name` to include dynamic values.
As an example of a job that previously wasn't monitored correctly, but is now:
```
class SendSignupEmail < Struct.new(:user_id)
def perform
end
def display_name
"SendSignupEmail - #{user_id}"
end
end
```
Before, the name detected by Scout would be `SendSignupEmail - 4828`, after, it will be `SendSignupEmail`.
> Better DelayedJob class naming

- lib/scout_apm/background_job_integrations/sidekiq.rb
This is the wrapper that gets used when you use ad-hoc backgrounding
with `MyClass.delay.myfunc(1,2,3)`
We were just getting the name of the wrapper, and now we expand it out
and read off the name of the actual function being called.
> Correctly extract name from Sidekiq DelayedClass

- lib/scout_apm/server_integrations/passenger.rb
Fix https://github.com/scoutapp/scout_apm_ruby/issues/149
Test locally with passenger 5.1.3 open source version
> Fix passenger using removed method

- lib/scout_apm/tracer.rb
- test/test_helper.rb
- test/unit/tracer_test.rb
While this is a pretty simple extraction, I used it as an opportunity to try to write a test or few and also poke around other bits of the codebase. I'm also interested in feedback about whether these tests are valuable.
Resolves #160
> Extracts ScoutApm::Tracer.instrument

- README.markdown
A green build instills confidence :slightly_smiling_face:
> Adds Travis-CI badge to README

- lib/scout_apm/agent/preconditions.rb
I guessed a bit at each `severity` here. I'm open to changing them based on feedback.
Resolves #130
> Preconditions have configurable severity

- Gemfile
Updating Gemfile to use https for RubyGems.
> Gemfile via SSL

- lib/scout_apm/instrument_manager.rb
> Fixes handling of disabled instruments

- lib/scout_apm/layer_converters/trace_converter.rb
This is a minimal change to stop recording spans if over 500 have been collected. 
If the limit is exceeded, a message is logged:
```
[11/20/18 10:41:07 -0700 dlite.local (47312)] DEBUG : Not recording additional spans for Controller/traces/tester. Over the span limit.
```
The goal: make it safe for us to run on a production server so we can see real traces.
This simply ignores additional spans. No additional info is collected at this point.
/cc @cschneid
> Not storing additional spans if over limit

- lib/scout_apm/instruments/action_view.rb
For Rails 6 support
Fixes #249
> Module prepend version of ActionView instruments

- lib/scout_apm/instruments/action_view.rb
> Handle nil virtual_path in templates

- lib/scout_apm/instruments/mongoid.rb
> Allow mongoid instrument to install on 7.x

- lib/scout_apm/app_server_load.rb
> Add the language and language_version keys to AppServerLoad

- CHANGELOG.markdown
> Update CHANGELOG entry for 2.5.3

- lib/scout_apm/utils/sql_sanitizer.rb
- lib/scout_apm/utils/sql_sanitizer_regex.rb
- lib/scout_apm/utils/sql_sanitizer_regex_1_8_7.rb
- test/unit/sql_sanitizer_test.rb
> Postgres Sanitization doesn't handle literal strings in SELECT clause

- Gemfile
This does not actually affect us, but I wanted to update it anyway rather
than simply ignoring the version.
In response to:
https://github.com/advisories/GHSA-jppv-gw3r-w3q8
> Update rake to avoid theoretical security issue

- lib/scout_apm/utils/sql_sanitizer.rb
- lib/scout_apm/utils/sql_sanitizer_regex.rb
- lib/scout_apm/utils/sql_sanitizer_regex_1_8_7.rb
- test/unit/sql_sanitizer_test.rb
Fixes https://github.com/scoutapp/apm/issues/2487
> Sanitize postgres update sql

- lib/scout_apm.rb
- lib/scout_apm/instrument_manager.rb
- lib/scout_apm/instruments/typhoeus.rb
Thank you @mjobin-mdsol for #371, rewrote much of it - Typhoeus is sorta a tricky library. I think I've got it nailed down though for basic and hydra operation. 
When we get some time to look into this, and if there's demand, we can do more to breakdown the calls inside of Hydra batches. But for now we just report the overall time and count.
> Add Typhoeus instrument for both single and hydra versions

- lib/scout_apm/instruments/typhoeus.rb
> Check that current_layer isn't nil in Typhoeus instrument

- lib/scout_apm/background_job_integrations/delayed_job.rb
Closes https://github.com/scoutapp/scout_apm_ruby/issues/372
> Update delayed job instrumentation present check

- lib/scout_apm/environment.rb
- lib/scout_apm/tracer.rb
- test/unit/tracer_test.rb
> Fix keyword args warning in instrument_method

- test/unit/auto_instrument/anonymous_block_value.rb
- test/unit/auto_instrument_test.rb
> Add a test for anonymous block arguments and autoinstrument

- CHANGELOG.markdown
- lib/scout_apm.rb
- lib/scout_apm/config.rb
- lib/scout_apm/exceptions.rb
Closes https://github.com/scoutapp/scout_apm_ruby/issues/230
> Handle exceptions during load of config file better

- lib/scout_apm/auto_instrument/instruction_sequence.rb
Closes https://github.com/scoutapp/scout_apm_ruby/issues/356
> Warn InstructionSequence only  if SCOUT_LOG_LEVEL is debug

- lib/scout_apm/background_job_integrations/sidekiq.rb
Closes https://github.com/scoutapp/scout_apm_ruby/issues/449
Note: this code path does not appear to be tested
> Fix bad Sidekiq::Processor patch causing failures on 6.5.0

- .github/workflows/release.yml
- CHANGELOG.markdown
- lib/scout_apm/version.rb
> Bump version

- .github/workflows/test.yml
> Add ruby 3.3 to test matrix

- .github/workflows/test.yml
- CHANGELOG.markdown
- gems/sqlite3-1.3.gemfile
remove ruby 2.1,2.2,2.3,2.4 from test matrix. Also remove sqlite3-1.3 gemfile used for those versions
> Remove old ruby support

- .github/workflows/test.yml
- CHANGELOG.markdown
- gems/rails7.gemfile
- gems/sidekiq7.gemfile
- gems/sidekiq8.gemfile
- lib/scout_apm/error_service/sidekiq.rb
- test/unit/background_job_integrations/sidekiq_test.rb
- test/unit/config_test.rb
- test/unit/sampling_test.rb
Closes #507 
- adds rails7 gemfile
- adds sidekiq7 to tests
- fixes some other deprecation warnings in tests
> handle sidekiq deprecation warning

- lib/scout_apm/sampling.rb
- test/unit/sampling_test.rb
> Support namespaced jobs in sample_jobs

- CHANGELOG.markdown
- lib/scout_apm/background_job_integrations/delayed_job.rb
- lib/scout_apm/error_service/error_record.rb
Handle delayed_job errors with some improved context.
Closes #565
> 565 delayed job errors
